// Platform page (/product), Section 3 — the Detect step, shown rather than
// described.
//
// Position (site-owner request, current session): "then use drone vision model
// output second then explaination of whole platform". This sits between the
// airframes and the operating loop, so the reader sees what the onboard vision
// produces before reading the cycle that "Detect" is step four of. The eyebrow
// label is therefore a topic, not a back reference.
//
// Site-owner request (current session): "for demo do one thing generate
// annotations from gemini flash 3.7 api key itself ... based on your judgement
// use best part as a gif there".
//
// PROVENANCE, and why the caption is worded the way it is:
//
// The footage is real Pawaac flight footage (public/videos/detection-demo.*,
// cut from D:\LionXdrones\website\vision13.mp4 at 21.3s). The bounding boxes
// and labels over it were generated by Gemini 3.7 Flash, NOT by Pawaac's own
// YOLO/ByteTrack pipeline. Those are different systems, so presenting this as
// the product's detector working would be a false capability claim — the exact
// thing this repo's content governance exists to prevent (see README ->
// Content governance).
//
// The caption therefore says "illustrative" explicitly. That word is not
// decorative: `simulatedLabel.ts`'s isValidIllustrativeLabel() requires
// "illustrative" or "simulated" in any label for concept/simulated output, and
// ProductDetectionDemo.test.tsx asserts this caption satisfies it. If the
// caption is ever softened into something that implies live product output,
// that test fails.
//
// Why this segment: the site owner asked for the best part to be chosen by
// judgement. 50 windows across all 14 raw videos were scored with Gemini 3.7
// Flash for how well clean annotations would read on them (camera stability,
// subject separation, subject size, crowding). This range won at 83/100 with
// "problem: none" and no privacy flags. It is trimmed to the first 2.5s of
// that window, because from about 2.6s onward the near-field two-wheelers stop
// being detected reliably and a viewer would notice the misses.
//
// The animated GIF the site owner asked for was produced too and is kept at
// public/videos/detection-demo.gif (1.89MB, 560px). It is not what renders
// here: a GIF cannot be paused, so it cannot satisfy WCAG 2.2.2 or this
// repo's reduced-motion rule, and it costs more than twice the bytes of the
// video at less than half the resolution. See DemoVideo.tsx.
import Reveal from "@/components/ui/Reveal";
import DemoVideo from "@/components/ui/DemoVideo";

export default function ProductDetectionDemo() {
  return (
    <section className="relative bg-bg px-6 py-24">
      <div className="mx-auto max-w-7xl">
        <div className="grid gap-10 md:grid-cols-[minmax(0,4fr)_minmax(0,7fr)] md:items-center md:gap-14">
          <Reveal>
            <p className="label">Detect</p>
            <h2 className="mt-3 text-heading font-display text-fg">
              What the aircraft is looking for
            </h2>
            <p className="mt-4 max-w-md text-body font-body text-muted">
              Every vehicle and person in frame gets a box and an identity that
              stays with it. That is the difference between a recording and a
              watch: the aircraft is not storing video for someone to scrub
              through later, it is deciding what is present, frame by frame.
            </p>
            <p className="mt-5 border-t border-line pt-4 text-sm leading-relaxed text-fg/75">
              The footage is real. The overlay is an illustration of the idea,
              not a measurement of the shipping detector.
            </p>
          </Reveal>

          <Reveal delay={0.1}>
            <DemoVideo
              src="/videos/detection-demo"
              poster="/images/detection-demo-poster.jpg"
              description="Aerial view of an urban road. Boxes and labels mark cars, trucks, motorcycles, auto rickshaws and pedestrians as they move through the frame, each keeping a numbered identity."
              caption="Illustrative detection overlay. Real Pawaac flight footage; annotations generated for demonstration, not output of the shipping detector."
            />
          </Reveal>
        </div>
      </div>
    </section>
  );
}
