"use client";

// The hero carousel's footage slide.
//
// Real Pawaac flight footage, re-encoded for the web from
// public/videos/droneFlyingVideo.mp4 (4.73 MB h264) into a 550 KB webm and a
// 707 KB mp4 with a matching poster frame. Audio is stripped: there is nothing
// to listen to, and a track-free file cannot be blocked by a browser's autoplay
// audio policy.
//
// No "illustrative" caption is required here, unlike ProductDetectionDemo. That
// one needed one because its bounding boxes were generated by a third-party
// model and would otherwise read as output from Pawaac's own detector. This is
// unannotated camera footage making no capability claim, so simulatedLabel.ts's
// rule does not apply to it.
//
// Colour, like SkyScenery's photograph, is a documented exception to the
// achromatic palette rather than a regression: the achromatic rule governs the
// interface, not camera footage. It is deliberately not grayscale-filtered, so
// it matches the colour sky photo it shares the carousel with.
//
// Playback rules:
//   - Autoplay is not the `autoPlay` attribute. It is started from an effect,
//     and only when the slide is active AND the visitor has not asked for
//     reduced motion, so the reduced-motion branch is real rather than cosmetic
//     and the rendered markup never depends on a client-only media query.
//   - `preload="none"` keeps the hero's LCP element (SkyScenery's photograph,
//     which is preloaded) from competing with a video the visitor may never
//     reach. The poster carries the frame until playback starts.
//   - The video pauses when the carousel moves away from it, so a slide that is
//     off-screen is not decoding frames.
import { useEffect, useRef } from "react";
import usePrefersReducedMotion from "@/hooks/usePrefersReducedMotion";

export default function HeroFlightVideo({ active }: { active: boolean }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const prefersReducedMotion = usePrefersReducedMotion();

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    if (!active || prefersReducedMotion) {
      // Guarded rather than called unconditionally: pausing an already paused
      // element is a no-op in a browser but a "Not implemented" console error
      // under jsdom, and this component is rendered by the homepage test suite.
      if (!video.paused) video.pause();
      return;
    }

    // play() rejects when the browser blocks it. That is not worth surfacing:
    // the poster frame stays visible and the carousel keeps working.
    const attempt = video.play();
    if (attempt && typeof attempt.catch === "function") {
      attempt.catch(() => {});
    }
  }, [active, prefersReducedMotion]);

  return (
    <div className="absolute inset-0 overflow-hidden">
      {/* Overscanned to match SkyScenery's `-inset-10` wrapper, so both slides
          crop identically and neither shows an edge gap. */}
      <video
        ref={videoRef}
        poster="/images/hero-flight-poster.jpg"
        muted
        loop
        playsInline
        preload="none"
        tabIndex={-1}
        className="absolute -inset-10 h-[calc(100%+5rem)] w-[calc(100%+5rem)] object-cover"
      >
        <source src="/videos/hero-flight.webm" type="video/webm" />
        <source src="/videos/hero-flight.mp4" type="video/mp4" />
      </video>

      {/* Same faint achromatic scan-line texture SkyScenery lays over its
          photograph, so the two slides read as one system rather than as a
          treated image next to an untreated video. */}
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage:
            "repeating-linear-gradient(to bottom, var(--color-white) 0px, var(--color-white) 1px, transparent 1px, transparent 4px)",
        }}
      />
    </div>
  );
}
